(() => {'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], enc=new TextEncoder(), dec=new TextDecoder();
const user=()=>localStorage.getItem('serenamind.fresh.active'), key=()=>`serenamind.fresh.recovery.${user()}`;
const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a))), unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
function read(){try{return JSON.parse(localStorage.getItem(key())||'{}')}catch{return {}}}function save(v){localStorage.setItem(key(),JSON.stringify(v))}function msg(id,t,ok=false){const e=$(id);if(e){e.textContent=t;e.classList.toggle('ok',ok)}}
function load(){const d=read();$$('#stimulusChoices input').forEach(x=>x.checked=(d.stimuli||[]).includes(x.value));$('#stimulusStatus').value=d.status||'Rustig';$('#stimulusHelps').value=d.helps||'';$('#tensionLevel').value=d.tension||1;$('#tensionSignals').value=d.signals||'';$('#tensionActions').value=d.actions||'';$('#orientationPlace').value=d.place||'';$('#orientationSentence').value=d.sentence||'';$('#orientationContact').value=d.contact||'';tension()}
function tension(){const labels=['Rustig','Oplopend','Hoog','Afstand en hulp nodig'];$('#tensionLabel').textContent=labels[+$('#tensionLevel').value-1]}
function collect(){return {stimuli:$$('#stimulusChoices input:checked').map(x=>x.value),status:$('#stimulusStatus').value,helps:$('#stimulusHelps').value,tension:+$('#tensionLevel').value,signals:$('#tensionSignals').value,actions:$('#tensionActions').value,place:$('#orientationPlace').value,sentence:$('#orientationSentence').value,contact:$('#orientationContact').value,updatedAt:new Date().toISOString()}}
async function derive(p,salt){const base=await crypto.subtle.importKey('raw',enc.encode(p),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function pack(data,p){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),k=await derive(p,salt),raw=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,enc.encode(JSON.stringify(data)));return {format:'SerenaMindShare',version:2,salt:b64(salt),iv:b64(iv),data:b64(raw)}}
async function open(o,p){const k=await derive(p,unb64(o.salt)),raw=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(o.iv)},k,unb64(o.data));return JSON.parse(dec.decode(raw))}
function download(name,obj){const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function boot(){load();$('#tensionLevel').oninput=tension;$('#saveSupportPlan').onclick=()=>{save(collect());msg('#supportMessage','Herstelplan lokaal bewaard.',true)};$('#showOrientation').onclick=()=>{const d=collect(),c=$('#orientationCard');c.innerHTML=`<b>Ik ben nu in:</b> ${escapeHtml(d.place||'mijn huidige omgeving')}<br><b>Helpende zin:</b> ${escapeHtml(d.sentence||'Ik ben nu hier.')}<br><b>Steuncontact:</b> ${escapeHtml(d.contact||'Nog niet ingevuld')}`;c.classList.remove('hidden')};$('#exportShare').onclick=async()=>{const p=$('#sharePassword').value;if(p.length<10)return msg('#shareStatus','Gebruik minimaal 10 tekens.');const d=JSON.parse(localStorage.getItem(`serenamind.fresh.data.${user()}`)||'{}'),selected=$$('#shareChoices input:checked').map(x=>x.value),payload={createdAt:new Date().toISOString(),message:$('#shareMessage').value,categories:selected,items:{}};if(selected.includes('checkins'))payload.items.checkins=d.checkins||[];if(selected.includes('focus'))payload.items.focus=d.focus||{};if(selected.includes('plan'))payload.items.plan=d.plan||{};if(selected.includes('support'))payload.items.support=read();download('serenamind-deelbestand.json',await pack(payload,p));msg('#shareStatus','Versleuteld deelbestand gemaakt.',true)};$('#importShare').onclick=async()=>{try{const f=$('#shareImportFile').files[0],o=JSON.parse(await f.text()),v=await open(o,$('#shareImportPassword').value);$('#sharedResult').innerHTML=`<div class="shared-block"><b>Ontvangen op ${new Date().toLocaleString('nl-NL')}</b><br>${escapeHtml(JSON.stringify(v,null,2))}</div>`}catch{msg('#shareStatus','Bestand of wachtwoord klopt niet.')}}}
function escapeHtml(v=''){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();