(() => { 'use strict';
const $=s=>document.querySelector(s), enc=new TextEncoder(), dec=new TextDecoder();
const active=()=>localStorage.getItem('serenamind.fresh.active');
const metaKey=()=>`serenamind.vault.meta.${active()}`, dataKey=()=>`serenamind.vault.data.${active()}`;
let key=null, entries=[], timer=null;
const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a))), unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function derive(password,salt,uses=['encrypt','decrypt']){const base=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,uses)}
async function verifier(k){return b64(await crypto.subtle.encrypt({name:'AES-GCM',iv:new Uint8Array(12)},k,enc.encode('SerenaMind-vault-check')))}
async function encrypt(k,value){const iv=crypto.getRandomValues(new Uint8Array(12)),raw=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,enc.encode(JSON.stringify(value)));return {iv:b64(iv),data:b64(raw)}}
async function decrypt(k,pack){const raw=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(pack.iv)},k,unb64(pack.data));return JSON.parse(dec.decode(raw))}
function status(id,t,ok=false){const e=$(id);if(e){e.textContent=t;e.classList.toggle('ok',ok)}}
function show(mode){$('#journalSetup').classList.toggle('hidden',mode!=='setup');$('#journalUnlock').classList.toggle('hidden',mode!=='locked');$('#journalOpen').classList.toggle('hidden',mode!=='open');}
function render(){ $('#journalList').innerHTML=entries.length?entries.map((x,i)=>`<article class="list-item"><button data-vault-delete="${i}">×</button><b>${escapeHtml(x.title||'Zonder titel')}</b><br><small>${new Date(x.at).toLocaleString('nl-NL')}</small><p>${escapeHtml(x.text)}</p></article>`).join(''):'<p class="fine">Nog geen versleutelde notities.</p>'; }
function escapeHtml(v=''){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function resetTimer(){clearTimeout(timer);if(!key)return;timer=setTimeout(lock,+($('#journalTimeout')?.value||5)*60000)}
async function persist(){localStorage.setItem(dataKey(),JSON.stringify(await encrypt(key,entries)));resetTimer()}
function lock(){key=null;entries=[];clearTimeout(timer);show(localStorage.getItem(metaKey())?'locked':'setup')}
async function create(){const p=$('#newJournalPassword').value,p2=$('#repeatJournalPassword').value;if(p.length<10)return status('#journalSetupMessage','Gebruik minimaal 10 tekens.');if(p!==p2)return status('#journalSetupMessage','Wachtwoorden zijn niet gelijk.');const salt=crypto.getRandomValues(new Uint8Array(16));key=await derive(p,salt);const check=await verifier(key);localStorage.setItem(metaKey(),JSON.stringify({salt:b64(salt),check}));entries=[];await persist();show('open');render()}
async function unlock(){try{const meta=JSON.parse(localStorage.getItem(metaKey())),k=await derive($('#journalPassword').value,unb64(meta.salt));if(await verifier(k)!==meta.check)throw Error();key=k;const pack=JSON.parse(localStorage.getItem(dataKey())||'null');entries=pack?await decrypt(key,pack):[];show('open');render();resetTimer()}catch{status('#journalUnlockMessage','Dagboekwachtwoord klopt niet.')}}
async function save(){const text=$('#journalText').value.trim();if(!text)return;entries.unshift({at:new Date().toISOString(),title:$('#journalTitle').value.trim(),text});await persist();$('#journalTitle').value='';$('#journalText').value='';render();status('#journalMessage','Versleuteld bewaard.',true)}
function download(name,obj){const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function boot(){show(localStorage.getItem(metaKey())?'locked':'setup');$('#createJournalVault').onclick=create;$('#unlockJournal').onclick=unlock;$('#lockJournal').onclick=lock;$('#saveJournal').onclick=save;$('#journalTimeout').onchange=resetTimer;$('#journalList').onclick=async e=>{if(e.target.dataset.vaultDelete!==undefined){entries.splice(+e.target.dataset.vaultDelete,1);await persist();render()}};$('#exportJournal').onclick=()=>download('serenamind-dagboek-versleuteld.json',{format:'SerenaMindVault',version:2,meta:JSON.parse(localStorage.getItem(metaKey())),payload:JSON.parse(localStorage.getItem(dataKey()))});$('#importJournalFile').onchange=async e=>{try{const o=JSON.parse(await e.target.files[0].text());if(o.format!=='SerenaMindVault')throw Error();localStorage.setItem(metaKey(),JSON.stringify(o.meta));localStorage.setItem(dataKey(),JSON.stringify(o.payload));lock();alert('Versleutelde back-up geïmporteerd.')}catch{alert('Ongeldig dagboekbestand.')}};document.addEventListener('click',resetTimer,{passive:true});document.addEventListener('keydown',resetTimer,{passive:true});document.addEventListener('visibilitychange',()=>{if(document.hidden)lock()});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();